name: My Workflow

on:
  push:

jobs:
  my-job:
    name: My Job (${{ matrix.hatchet-protocol }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hatchet-protocol: [holster, carve, cleave, rampage]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Increase disk space (${{ matrix.hatchet-protocol }})
        uses: wimpysworld/nothing-but-nix@v5
        with:
          hatchet-protocol: ${{ matrix.hatchet-protocol }}
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@v6.1.3
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Check flake
        run: nix flake check
