name: My Workflow

on:
  push:

jobs:
  my-job:
    name: My Job (${{ matrix.hatchet-protocol }}, nix_on_tmpfs: ${{ matrix.nix_on_tmpfs }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hatchet-protocol: [holster, carve, cleave, rampage]
        nix_on_tmpfs: [true, false]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Increase disk space (${{ matrix.hatchet-protocol }})
        uses: wimpysworld/nothing-but-nix@v5
        with:
          hatchet-protocol: ${{ matrix.hatchet-protocol }}
      - name: Install Nix (nix_on_tmpfs: ${{ matrix.nix_on_tmpfs }})
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_on_tmpfs: ${{ matrix.nix_on_tmpfs }}
      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@v6.1.3
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Check flake
        run: nix flake check
